### ISSUE TITLE
Python :  Duplicate entry '50:C7:BF:0D:22:63' for key 'PRIMARY'

### ISSUE THREAD

**Issue by matteyeux** [white-wolf-project/ragnarok#48]
On overwrite pas les données, donc ça nous donne des erreurs par rapport à la clé primaire, je te laisse corriger ça
```
$ ./xmlparser.py ragnarok.xml
IEEE 802.11i/WPA2 Version 1
1
Traceback (most recent call last):
  File "./xmlparser.py", line 79, in <module>
    insert_info_ap(conn, mac, essid, time, 1, channel, beacon, signal, frequency, 1, mac_rasb)
  File "./xmlparser.py", line 12, in insert_info_ap
    curs.execute(sql)
  File "/home/mathieu/.local/lib/python3.5/site-packages/mysql/connector/cursor.py", line 566, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/mathieu/.local/lib/python3.5/site-packages/mysql/connector/connection.py", line 530, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/mathieu/.local/lib/python3.5/site-packages/mysql/connector/connection.py", line 432, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '50:C7:BF:0D:22:63' for key 'PRIMARY'
```

**Comment by eehP** [comment]
Plus d'erreur de PrimaryKey Double si on réinitialise bien la DB a chaque fois.
(Je travaille sur un moyen de garder les anciens AP dans la DB)
